#!/bin/sh

# kill children when foreground is killed
trap "trap - TERM && kill -- -$$" INT TERM EXIT

# subshell to start history window
(cd hyperboard; echo "starting hyperboard!"; ./hyperboard $1) &

# start hyperfind
./hyperfind $1
