#!/bin/sh

# kill children when foreground is killed
trap "trap - TERM && kill -- -$$" INT TERM EXIT

# subshell to start history window
(
CWD=$(pwd);
cd hyperboard;
echo "starting hyperboard!";
echo "CWD";
echo $CWD;
echo "PWD";
echo $(pwd);
./hyperboard $1 $CWD;
) &

# start hyperfind
./hyperfind $1
